services:
  - type: web
    name: agrodoctor
    env: python
    plan: free
    region: Singapore (Southeast Asia)
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate --noinput && gunicorn agrodoctor.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    autoDeploy: true
    healthCheckPath: /
envVarGroups:
  - name: my-env-group    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_SETTINGS_MODULE
        value: agrodoctor.settings
      - key: SECRET_KEY
        fromSecret: DJANGO_SECRET_KEY
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: DEBUG
        value: "False"
