# Generated by Django 5.2.4 on 2025-07-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_prediction_options_remove_prediction_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='causes',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='description',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='image',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='effectiveness',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='precautions',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='treatment_type',
        ),
    ]
